(define (make-account balance password)
  (let ((count 0))
	(define (withdraw amount)
	  (if (>= balance amount)
		  (begin (set! balance (- balance amount))
				 balance)
		  "Insufficient funds"))
	(define (deposit amount)
	  (set! balance (+ balance amount))
	  balance)
	(define (dispatch m)
	  (cond ((eq? m 'withdraw) withdraw)
			((eq? m 'deposit) deposit)
			(else (error "Unknown request: MAKE-ACCOUNT"
						 m))))
	(define (call-the-cops x)
	  "Boop beep you were arrested")
	(lambda (p m)
	  (if (equal? p password)
		  (begin
			(set! count 0)
			(dispatch m))
		  (begin
			(set! count (1+ count))
			(if (> count 7)
				call-the-cops
				(lambda (x) "Incorrect password")))))))
