(define (make-account balance password)
  (define (withdraw amount)
	(if (>= balance amount)
		(begin (set! balance (- balance amount))
			   balance)
		"Insufficient funds"))
  (define (deposit amount)
	(set! balance (+ balance amount))
	balance)
  (define (newacc password)
	(lambda (p m)
	  (if (equal? p password)
		  (dispatch m)
		  (lambda (x) "Incorrect password"))))
  (define (dispatch m)
	(cond ((eq? m 'withdraw) withdraw)
		  ((eq? m 'deposit) deposit)
		  ((eq? m 'newacc) newacc)
		  (else (error "Unknown request: MAKE-ACCOUNT"
					   m))))
  (newacc password))


(define (make-joint acc pass newpass)
  ((acc pass 'newacc) newpass))
